name: Lazy Framework Patcher

on:
  workflow_dispatch:
    inputs:
      framework_url:
        description: 'Direct URL to framework.jar'
        required: false
        type: string
      services_url:
        description: 'Direct URL to services.jar'
        required: false
        type: string
      core_url:
        description: 'Direct URL to core.jar'
        required: false
        type: string
      myapp_url:
        description: 'Direct URL to myapp.apk'
        required: false
        type: string

env:
  ARTIFACT_DIR: patched_files_${{ github.run_id }}

jobs:
  patch:
    name: Patch Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget

      - name: Create directories
        run: |
          mkdir -p rom/system/system/framework
          mkdir -p rom/system/system/app
          mkdir -p "${{ env.ARTIFACT_DIR }}"

      - name: Download framework.jar
        if: ${{ inputs.framework_url != '' }}
        run: |
          wget "${{ inputs.framework_url }}" -O rom/system/system/framework/framework.jar

      - name: Download services.jar
        if: ${{ inputs.services_url != '' }}
        run: |
          wget "${{ inputs.services_url }}" -O rom/system/system/framework/services.jar

      - name: Download core.jar
        if: ${{ inputs.core_url != '' }}
        run: |
          wget "${{ inputs.core_url }}" -O rom/system/system/framework/core.jar

      - name: Download myapp.apk
        if: ${{ inputs.myapp_url != '' }}
        run: |
          wget "${{ inputs.myapp_url }}" -O rom/system/system/app/myapp.apk

      - name: Make patcher executable
        run: chmod +x lazy_patcher.sh

      - name: Run patcher
        run: |
          ./lazy_patcher.sh rom
          echo "Patcher completed successfully"

      - name: Collect artifacts
        run: |
          find rom/system/system/framework -type f -name '*.jar' -exec cp {} "${{ env.ARTIFACT_DIR }}/" \;
          find rom/system/system/app -type f -name '*.apk' -exec cp {} "${{ env.ARTIFACT_DIR }}/" \;
          echo "Generated artifacts:"
          ls -lh "${{ env.ARTIFACT_DIR }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: patched-files
          path: ${{ env.ARTIFACT_DIR }}/*
          retention-days: 7
