name: Lazy Framework Patcher

on:
  workflow_dispatch:
    inputs:
      file_urls:
        description: 'Paste URLs for JAR/APK files (one per line, e.g., framework.jar, services.jar, core.jar, myapp.apk)'
        required: true
        type: string

env:
  ARTIFACT_DIR: patched_files_${{ github.run_id }}
  BUILD_DATE: ${{ github.run_id }}

jobs:
  validate:
    name: Validate Input
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.check-input.outputs.valid }}
    steps:
      - name: Check inputs
        id: check-input
        run: |
          if [[ -z "${{ inputs.file_urls }}" ]]; then
            echo "::error::At least one file URL must be provided"
            echo "valid=false" >> $GITHUB_OUTPUT
          else
            echo "valid=true" >> $GITHUB_OUTPUT
          fi

  patch:
    name: Patch Files
    needs: validate
    if: ${{ needs.validate.outputs.valid == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          echo "BUILD_DATE=$(date -u +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Create directories
        run: |
          mkdir -p rom/system/system/framework
          mkdir -p rom/system/system/app
          mkdir -p "${{ env.ARTIFACT_DIR }}"

      - name: Download provided files
        run: |
          echo "${{ inputs.file_urls }}" > file_urls.txt
          while IFS= read -r url; do
            [ -z "$url" ] && continue
            fname=$(basename "$url")
            ext="${fname##*.}"
            if [[ "$ext" == "jar" ]]; then
              dest="rom/system/system/framework/$fname"
              mkdir -p rom/system/system/framework
            elif [[ "$ext" == "apk" ]]; then
              dest="rom/system/system/app/$fname"
              mkdir -p rom/system/system/app
            else
              echo "Skipping unsupported file: $fname"
              continue
            fi
            wget -q --show-progress "$url" -O "$dest"
            echo "Downloaded $dest"
          done < file_urls.txt

      - name: Make patcher executable
        run: chmod +x lazy_patcher.sh

      - name: Run patcher
        run: |
          ./lazy_patcher.sh rom
          echo "Patcher completed successfully"

      - name: Collect artifacts
        run: |
          find rom/system/system/framework -type f -name '*.jar' -exec cp {} "${{ env.ARTIFACT_DIR }}/" \;
          find rom/system/system/app -type f -name '*.apk' -exec cp {} "${{ env.ARTIFACT_DIR }}/" \;
          echo "Generated artifacts:"
          ls -lh "${{ env.ARTIFACT_DIR }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: patched-files
          path: ${{ env.ARTIFACT_DIR }}/*
          retention-days: 7
