name: Lazy Patcher V1

on:
  workflow_dispatch:
    inputs:
      framework_jar_url:
        description: 'URL to framework.jar (optional)'
        required: false
      services_jar_url:
        description: 'URL to services.jar (optional)'
        required: false

env:
  ARTIFACT_DIR: patched_jars_${{ github.run_id }}_${{ github.run_attempt }}
  BUILD_DATE: $(date +'%Y%m%d-%H%M')

jobs:
  validate-input:
    name: Validate Inputs
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.validation.outputs.valid }}
    steps:
      - name: Check Inputs
        id: validation
        run: |
          if [[ -z "${{ inputs.framework_jar_url }}" && -z "${{ inputs.services_jar_url }}" ]]; then
            echo "::error::At least one JAR URL must be provided (framework or services)"
            echo "valid=false" >> $GITHUB_OUTPUT
          else
            echo "valid=true" >> $GITHUB_OUTPUT
          fi

  patch-jars:
    name: Patch JAR Files
    needs: validate-input
    if: ${{ needs.validate-input.outputs.valid == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget

      - name: Create workspace
        run: |
          mkdir -p rom/system/system/framework
          mkdir -p "${{ env.ARTIFACT_DIR }}"

      - name: Download framework.jar (if provided)
        if: ${{ inputs.framework_jar_url != '' }}
        run: |
          echo "Downloading framework.jar from ${{ inputs.framework_jar_url }}"
          wget -q --show-progress "${{ inputs.framework_jar_url }}" -O rom/system/system/framework/framework.jar
          echo "Downloaded $(ls -lh rom/system/system/framework/framework.jar)"

      - name: Download services.jar (if provided)
        if: ${{ inputs.services_jar_url != '' }}
        run: |
          echo "Downloading services.jar from ${{ inputs.services_jar_url }}"
          wget -q --show-progress "${{ inputs.services_jar_url }}" -O rom/system/system/framework/services.jar
          echo "Downloaded $(ls -lh rom/system/system/framework/services.jar)"

      - name: Make patcher executable
        run: chmod +x lazy_patcher.sh

      - name: Run patcher script
        run: |
          .lazy_patcher.sh rom
          echo "Patcher completed successfully"

      - name: Collect patched artifacts
        run: |
          cd "${{ env.ARTIFACT_DIR }}"
          
          if [[ -f ../rom/system/system/framework/framework.jar ]]; then
            cp ../rom/system/system/framework/framework.jar "framework_patched_${{ env.BUILD_DATE }}.jar"
          fi
          
          if [[ -f ../rom/system/system/framework/services.jar ]]; then
            cp ../rom/system/system/framework/services.jar "services_patched_${{ env.BUILD_DATE }}.jar"
          fi
          
          echo "Artifacts:"
          ls -lh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: patched-jars
          path: ${{ env.ARTIFACT_DIR }}/*.jar
